- hosts: docker
  become: true
  roles:
    - docker

- hosts: swarm_init
  become: true
  vars:
    swarm_info:
  roles:
    - swarm_init

- hosts: swarm_manager
  become: true
  vars:
    swarm_info:
  roles:
  - swarm_manager

- hosts: swarm_worker
  become: true
  vars:
    swarm_info:
  roles:
  - swarm_worker
